<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RekapTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('rekap')->delete();
        
        DB::table('rekap')->insert(array (
            0 => 
            array (
                'id' => 1,
                'kode_barang' => '7142',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'Sclamp',
                'seri' => '-',
                'jumlah' => 50,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 50,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:06:17',
                'updated_at' => '2024-12-02 14:06:17',
            ),
            1 => 
            array (
                'id' => 2,
                'kode_barang' => '7140',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Sleeve Besar',
                'seri' => '60mm',
                'jumlah' => 15,
                'satuan' => 'pack',
                'rasio' => 50,
                'hasil' => 750,
                'detail_jumlah' => 0,
                'stok_awal' => 750,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:14:24',
                'updated_at' => '2024-12-02 14:14:24',
            ),
            2 => 
            array (
                'id' => 3,
                'kode_barang' => '7118',
                'kategori' => 'PIGTAIL',
                'nama_barang' => 'Pigtail',
                'seri' => '0.9mm',
                'jumlah' => 40,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 40,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:20:52',
                'updated_at' => '2024-12-02 14:20:52',
            ),
            3 => 
            array (
                'id' => 4,
                'kode_barang' => '7119',
                'kategori' => 'PIGTAIL',
                'nama_barang' => 'Pigtail',
                'seri' => '2mm',
                'jumlah' => 40,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 40,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:21:56',
                'updated_at' => '2024-12-02 14:21:56',
            ),
            4 => 
            array (
                'id' => 5,
                'kode_barang' => '7121',
                'kategori' => 'SPILTTER',
                'nama_barang' => 'S 1:4',
                'seri' => '-',
                'jumlah' => 5,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 5,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:25:43',
                'updated_at' => '2024-12-02 14:25:43',
            ),
            5 => 
            array (
                'id' => 6,
                'kode_barang' => '7136',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Klem Kabel',
                'seri' => '7mm',
                'jumlah' => 100,
                'satuan' => 'pack',
                'rasio' => 35,
                'hasil' => 3500,
                'detail_jumlah' => 0,
                'stok_awal' => 3500,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:34:52',
                'updated_at' => '2024-12-02 14:34:52',
            ),
            6 => 
            array (
                'id' => 7,
                'kode_barang' => '7138',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Kabel Ties',
                'seri' => '20cm',
                'jumlah' => 25,
                'satuan' => 'pack',
                'rasio' => 100,
                'hasil' => 2500,
                'detail_jumlah' => 0,
                'stok_awal' => 2500,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:38:01',
                'updated_at' => '2024-12-02 14:38:01',
            ),
            7 => 
            array (
                'id' => 8,
                'kode_barang' => '7137',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Solasi',
                'seri' => 'National',
                'jumlah' => 24,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 24,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:39:09',
                'updated_at' => '2024-12-02 14:39:09',
            ),
            8 => 
            array (
                'id' => 9,
                'kode_barang' => '7102',
                'kategori' => 'Kabel',
                'nama_barang' => 'Fiber Optic',
                'seri' => '1 Core',
                'jumlah' => 6,
                'satuan' => 'roll',
                'rasio' => 1000,
                'hasil' => 5900,
                'detail_jumlah' => 900,
                'stok_awal' => 6000,
                'in' => NULL,
                'out' => 100,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:21:10',
                'updated_at' => '2024-12-06 10:57:14',
            ),
            9 => 
            array (
                'id' => 10,
                'kode_barang' => '7133',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'Joint Closure',
                'seri' => 'Kapal Selam',
                'jumlah' => 6,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 6,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:24:41',
                'updated_at' => '2024-11-19 09:24:41',
            ),
            10 => 
            array (
                'id' => 11,
                'kode_barang' => '7149',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Hose Clamp',
                'seri' => 'Besar',
                'jumlah' => 10,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 10,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:26:50',
                'updated_at' => '2024-11-19 09:26:50',
            ),
            11 => 
            array (
                'id' => 12,
                'kode_barang' => '7122',
                'kategori' => 'SPILTTER',
                'nama_barang' => 'S 1:8',
                'seri' => '-',
                'jumlah' => 2,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 2,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:29:54',
                'updated_at' => '2024-11-19 09:29:54',
            ),
            12 => 
            array (
                'id' => 13,
                'kode_barang' => '7120',
                'kategori' => 'SPILTTER',
                'nama_barang' => 'S 1:2',
                'seri' => '-',
                'jumlah' => 2,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 2,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:30:53',
                'updated_at' => '2024-11-19 09:30:53',
            ),
            13 => 
            array (
                'id' => 14,
                'kode_barang' => '7126',
                'kategori' => 'SPLITTER RATIO',
                'nama_barang' => 'SR 90%:10%',
                'seri' => '-',
                'jumlah' => 2,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 2,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:34:51',
                'updated_at' => '2024-11-19 09:34:51',
            ),
            14 => 
            array (
                'id' => 15,
                'kode_barang' => '7117',
                'kategori' => 'CPE & Aksesoris',
                'nama_barang' => 'Roset',
                'seri' => '-',
                'jumlah' => 40,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 40,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:36:40',
                'updated_at' => '2024-11-19 09:36:40',
            ),
            15 => 
            array (
                'id' => 16,
                'kode_barang' => '7132',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'Joint Closure',
                'seri' => 'Kotak',
                'jumlah' => 5,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 5,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:38:25',
                'updated_at' => '2024-11-19 09:38:25',
            ),
            16 => 
            array (
                'id' => 17,
                'kode_barang' => '7134',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'ODP',
                'seri' => 'Double Lock',
                'jumlah' => 5,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'stok_awal' => 5,
                'in' => NULL,
                'out' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:42:09',
                'updated_at' => '2024-11-19 09:42:09',
            ),
        ));
        
        
    }
}