<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StokGudangTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('stok_gudang')->delete();
    
        DB::table('stok_gudang')->insert(array (
            0 => 
            array (
                'id' => 1,
                'kode_barang' => '222',
                'kategori' => 'Elektronik',
                'nama_barang' => 'Kipas Angin',
                'seri' => '-',
                'jumlah' => 8,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak Bawah',
                'foto' => 'img/1745387150-iS0Mz2Ve6mObPvTyfmqsgiyeX7HwJfrPqjt5y6Jx.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-03-06 15:34:08',
                'updated_at' => '2025-04-27 19:08:55',
            ),
            1 => 
            array (
                'id' => 2,
                'kode_barang' => '6756',
                'kategori' => 'Alat Tulis',
                'nama_barang' => 'Pulpen',
                'seri' => 'joyko',
                'jumlah' => 90,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Laci Meja',
                'foto' => 'img/1745386608-PyOFz5CvzPQW9e3nzb5u14Qybulm99Wob2AUctEC.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-03-06 12:36:48',
                'updated_at' => '2025-04-27 19:08:55',
            ),
            2 => 
            array (
                'id' => 3,
                'kode_barang' => '8899',
                'kategori' => 'Perkakas',
                'nama_barang' => 'Obeng Set',
                'seri' => 'OB-SET-X',
                'jumlah' => 13,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Lemari Kecil',
                'foto' => 'img/1745386668-s8RYc48Dq3z880suZboD7LyRDTHOJybiQbC2CfGJ.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-04-23 12:37:48',
                'updated_at' => '2025-04-25 00:32:39',
            ),
            3 => 
            array (
                'id' => 4,
                'kode_barang' => '4455',
                'kategori' => 'Kebersihan',
                'nama_barang' => 'Tisu Gulung',
                'seri' => '-',
                'jumlah' => 20,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Gudang Belakang',
                'foto' => 'img/1745386728-iFskBudC1sBTMs46Lkv0kEBhZltQz9mfS2AfQJ0e.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-04-11 12:38:48',
                'updated_at' => '2024-04-11 12:38:48',
            ),
            4 => 
            array (
                'id' => 5,
                'kode_barang' => '6762',
                'kategori' => 'Kebersihan',
                'nama_barang' => 'Masker',
                'seri' => 'Sensi',
                'jumlah' => 25,
                'satuan' => 'pack',
                'rasio' => 10,
                'hasil' => 243,
                'detail_jumlah' => 3,
                'lokasi' => 'Lemari Atas',
                'foto' => 'img/1745386861-dTydiWwmiOrYLVkpLNmYZjQZI7O00OjD5pLyYSW7.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2020-05-08 12:41:01',
                'updated_at' => '2025-04-27 19:08:55',
            ),
            5 => 
            array (
                'id' => 6,
                'kode_barang' => '3210',
                'kategori' => 'Dapur',
                'nama_barang' => 'Dispenser Air',
                'seri' => 'DPN-ZX',
                'jumlah' => 11,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Ruang Istirahat',
                'foto' => 'img/1745386918-HodJmkSVw698zutOaj8TnsBsGmU0HueSPXrxURZO.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-02-10 12:41:58',
                'updated_at' => '2025-04-25 00:32:39',
            ),
            6 => 
            array (
                'id' => 7,
                'kode_barang' => '1234',
                'kategori' => 'Elektronik',
                'nama_barang' => 'Kulkas Mini',
                'seri' => 'KM-2025',
                'jumlah' => 14,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Gudang Depan',
                'foto' => 'img/1745507729-HIcu2Wwt4gOZnBdaVp3F44OnXbstHmB8frURr4Qi.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-04-24 22:15:30',
                'updated_at' => '2025-04-25 00:32:39',
            ),
            7 => 
            array (
                'id' => 8,
                'kode_barang' => '5678',
                'kategori' => 'Alat Tulis',
                'nama_barang' => 'Pensil',
                'seri' => 'B-2B',
                'jumlah' => 15,
                'satuan' => 'pack',
                'rasio' => 10,
                'hasil' => 150,
                'detail_jumlah' => 0,
                'lokasi' => 'Meja Kerja',
                'foto' => 'img/1745507802-A3e1o7CDIQg38kwwH6eYdtoiJ9yutAAwT3ra6Xn5.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-01-03 22:16:42',
                'updated_at' => '2025-01-03 22:16:42',
            ),
            8 => 
            array (
                'id' => 9,
                'kode_barang' => '8900',
                'kategori' => 'Perkakas',
                'nama_barang' => 'Gergaji Besi',
                'seri' => 'GB-001',
                'jumlah' => 10,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Lemari Besar',
                'foto' => 'img/1745507889-xrNeyEhW8JSmExJ0lLzNxnz2PqOcSB4VCJqpc8tp.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-02-22 22:18:09',
                'updated_at' => '2025-02-22 22:18:09',
            ),
            9 => 
            array (
                'id' => 10,
                'kode_barang' => '1122',
                'kategori' => 'Kebersihan',
                'nama_barang' => 'Sabun Cair',
                'seri' => 'SC-500ml',
                'jumlah' => 50,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak Penyimpanan',
                'foto' => 'img/1745507933-aqYDTnyE9nZIggYJmb8ib2mw1FwY7YZPCcD8Feto.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-03-20 22:18:53',
                'updated_at' => '2025-03-20 22:18:53',
            ),
            10 => 
            array (
                'id' => 11,
                'kode_barang' => '3344',
                'kategori' => 'Kebersihan',
                'nama_barang' => 'Pembersih Lantai',
                'seri' => 'PL-1L',
                'jumlah' => 12,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Gudang Belakang',
                'foto' => 'img/1745507987-uIzKoRT0kTOEebi9wcDRQUiViKJrBPh1AE1m7M38.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-04-24 22:19:48',
                'updated_at' => '2025-04-24 22:19:48',
            ),
            11 => 
            array (
                'id' => 12,
                'kode_barang' => '5567',
                'kategori' => 'Elektronik',
                'nama_barang' => 'Televisi 32"',
                'seri' => 'TV-32A',
                'jumlah' => 14,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Ruang Rapat',
                'foto' => 'img/1745508029-kSXGWh8FtRIyL4RrqHYBFiFhc3M25MtWQY2emFAu.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-05-15 22:20:30',
                'updated_at' => '2025-04-25 00:32:39',
            ),
            12 => 
            array (
                'id' => 13,
                'kode_barang' => '7788',
                'kategori' => 'Perkakas',
                'nama_barang' => 'Palu',
                'seri' => 'P-001',
                'jumlah' => 15,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Lemari Kecil',
                'foto' => 'img/1745508082-6PpbgwOgzrEGY5QbA66SA9bVp1enfkqdQoGEmtY5.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-06-13 22:21:22',
                'updated_at' => '2025-06-13 22:21:22',
            ),
            13 => 
            array (
                'id' => 14,
                'kode_barang' => '9000',
                'kategori' => 'Dapur',
                'nama_barang' => 'Mesin Cuci Piring',
                'seri' => 'MCP-300',
                'jumlah' => 7,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Dapur Utama',
                'foto' => 'img/1745508128-SbjqBOFFYKwieBB0MO6YnMv3U3V4KlVVHs5N3gHf.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-07-18 22:22:08',
                'updated_at' => '2025-04-25 00:32:39',
            ),
            14 => 
            array (
                'id' => 15,
                'kode_barang' => '3345',
                'kategori' => 'Elektronik',
                'nama_barang' => 'Laptop',
                'seri' => 'HP-15',
                'jumlah' => 12,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Meja Kerja',
                'foto' => 'img/1745508165-fDyLgRjbf6MMHpWveD3w7Sf8KHJlZ8q6mNOBLWWp.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-08-08 22:22:45',
                'updated_at' => '2025-04-25 00:32:39',
            ),
            15 => 
            array (
                'id' => 16,
                'kode_barang' => '6677',
                'kategori' => 'Kebersihan',
                'nama_barang' => 'Pembersih Kaca',
                'seri' => 'PK-500ml',
                'jumlah' => 30,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak Kaca',
                'foto' => 'img/1745508218-T5t6LGzk52n1wevgjv2d7IbqdKaKf7buWdUhI39D.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-09-25 22:23:38',
                'updated_at' => '2025-09-25 22:23:38',
            ),
            16 => 
            array (
                'id' => 17,
                'kode_barang' => '8888',
                'kategori' => 'Elektronik',
                'nama_barang' => 'AC Split',
                'seri' => 'AC-1.5PK',
                'jumlah' => 10,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Gudang Utama',
                'foto' => 'img/1745508273-5po8cE8qBSuSDbyXZbqZ8dhoPgQ0v1Dc1Jc1LcoM.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-10-03 22:24:33',
                'updated_at' => '2025-04-25 00:32:39',
            ),
            17 => 
            array (
                'id' => 18,
                'kode_barang' => '2233',
                'kategori' => 'Alat Tulis',
                'nama_barang' => 'Marker',
                'seri' => 'MK-001',
                'jumlah' => 120,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Laci Meja',
                'foto' => 'img/1745508306-dKTfwkAmPGd8mdNJyNrik8q2Ow1c3RWkExKtiKOl.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-11-08 22:25:06',
                'updated_at' => '2025-11-08 22:25:06',
            ),
            18 => 
            array (
                'id' => 19,
                'kode_barang' => '4456',
                'kategori' => 'Perkakas',
                'nama_barang' => 'Tang',
                'seri' => 'T-100',
                'jumlah' => 15,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Lemari Kecil',
                'foto' => 'img/1745508344-4QAzzQ5aVZa93MujfIW9poLtEXezyBG0VtU487m7.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2025-12-19 22:25:44',
                'updated_at' => '2025-12-19 22:25:44',
            ),
            19 => 
            array (
                'id' => 20,
                'kode_barang' => '9988',
                'kategori' => 'Dapur',
                'nama_barang' => 'Blender',
                'seri' => 'BL-202',
                'jumlah' => 8,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Ruang Istirahat',
                'foto' => 'img/1745508420-8WtIwMSR8JY1W1Mf967joNU3SlHpEN6i1nMPeUXG.jpg',
                'input_by' => 'kevin',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2023-04-05 22:27:00',
                'updated_at' => '2025-04-25 00:32:39',
            ),
        ));
        
        
    }
}