<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StokGudangTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('stok_gudang')->delete();
        
        DB::table('stok_gudang')->insert(array (
            0 => 
            array (
                'id' => 1,
                'kode_barang' => '7142',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'Sclamp',
                'seri' => '-',
                'jumlah' => 50,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 2',
                'foto' => 'img/1733123177-Skpck4dGFKydNRXLs9Vst9I7EXlaQbCFDKg4eZw0.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:06:17',
                'updated_at' => '2024-12-02 14:06:17',
            ),
            1 => 
            array (
                'id' => 2,
                'kode_barang' => '7140',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Sleeve Besar',
                'seri' => '60mm',
                'jumlah' => 15,
                'satuan' => 'pack',
                'rasio' => 50,
                'hasil' => 750,
                'detail_jumlah' => 0,
                'lokasi' => 'Rak 2',
                'foto' => 'img/1733123664-m64vlPqlqh15ejU42XkmChelor24EWWLsxLulXkc.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:14:24',
                'updated_at' => '2024-12-02 14:14:24',
            ),
            2 => 
            array (
                'id' => 3,
                'kode_barang' => '7118',
                'kategori' => 'PIGTAIL',
                'nama_barang' => 'Pigtail',
                'seri' => '0.9mm',
                'jumlah' => 40,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 4',
                'foto' => 'img/1733124052-sDVoDUcGWrF9KWPbrXhexrycHUptp1q9bVDMMBEG.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:20:52',
                'updated_at' => '2024-12-02 14:20:52',
            ),
            3 => 
            array (
                'id' => 4,
                'kode_barang' => '7119',
                'kategori' => 'PIGTAIL',
                'nama_barang' => 'Pigtail',
                'seri' => '2mm',
                'jumlah' => 40,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 4',
                'foto' => 'img/1733124116-6bwz4NwAt6X5agX8HS9VOQZF3muY0VXp7hsAISTB.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:21:56',
                'updated_at' => '2024-12-02 14:21:56',
            ),
            4 => 
            array (
                'id' => 5,
                'kode_barang' => '7121',
                'kategori' => 'SPILTTER',
                'nama_barang' => 'S 1:4',
                'seri' => '-',
                'jumlah' => 5,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 2',
                'foto' => 'img/1733124343-GS0h46itstC7aUBRxS9u8Kg8O3jqLjY6HA6wnQdR.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:25:43',
                'updated_at' => '2024-12-02 14:25:43',
            ),
            5 => 
            array (
                'id' => 6,
                'kode_barang' => '7136',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Klem Kabel',
                'seri' => '7mm',
                'jumlah' => 100,
                'satuan' => 'pack',
                'rasio' => 35,
                'hasil' => 3500,
                'detail_jumlah' => 0,
                'lokasi' => 'Rak 3',
                'foto' => 'img/1733124892-CXH0QPjB84TUMFYK3Y7uAFuz5BpIX0Vd25nN8sqP.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:34:52',
                'updated_at' => '2024-12-02 14:34:52',
            ),
            6 => 
            array (
                'id' => 7,
                'kode_barang' => '7138',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Kabel Ties',
                'seri' => '20cm',
                'jumlah' => 25,
                'satuan' => 'pack',
                'rasio' => 100,
                'hasil' => 2500,
                'detail_jumlah' => 0,
                'lokasi' => 'Rak 3',
                'foto' => 'img/1733125081-MuVtxbArSikRb60L5OF4KTD8SGq4kl5sHbPgogPH.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:38:01',
                'updated_at' => '2024-12-02 14:38:01',
            ),
            7 => 
            array (
                'id' => 8,
                'kode_barang' => '7137',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Solasi',
                'seri' => 'National',
                'jumlah' => 24,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 3',
                'foto' => 'img/1733125149-ynv5oDrts927u0QBrOFvT6cWhKQvLVy8vBAwgPGD.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-02 14:39:09',
                'updated_at' => '2024-12-02 14:39:09',
            ),
            8 => 
            array (
                'id' => 9,
                'kode_barang' => '7102',
                'kategori' => 'Kabel',
                'nama_barang' => 'Fiber Optic',
                'seri' => '1 Core',
                'jumlah' => 6,
                'satuan' => 'roll',
                'rasio' => 1000,
                'hasil' => 5900,
                'detail_jumlah' => 900,
                'lokasi' => 'Lantai bawah',
                'foto' => 'img/1733192470-nVXq11MMb2Ze3vRhMDpC3XasVPsP9Pr99IIB7euj.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:21:10',
                'updated_at' => '2024-12-06 10:57:14',
            ),
            9 => 
            array (
                'id' => 10,
                'kode_barang' => '7133',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'Joint Closure',
                'seri' => 'Kapal Selam',
                'jumlah' => 6,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 5',
                'foto' => 'img/1733192681-0Y7S8FWrDalyrqb9ZnGDL4i4puo7pZhW4M1RONm0.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:24:41',
                'updated_at' => '2024-11-19 09:24:41',
            ),
            10 => 
            array (
                'id' => 11,
                'kode_barang' => '7149',
                'kategori' => 'Lain-lain',
                'nama_barang' => 'Hose Clamp',
                'seri' => 'Besar',
                'jumlah' => 10,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 1',
                'foto' => 'img/1733192810-ip5pxtHxFqf7S2sP8Z4glF7ydCKvfo0faFj4KHJq.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:26:50',
                'updated_at' => '2024-11-19 09:26:50',
            ),
            11 => 
            array (
                'id' => 12,
                'kode_barang' => '7122',
                'kategori' => 'SPILTTER',
                'nama_barang' => 'S 1:8',
                'seri' => '-',
                'jumlah' => 2,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 2',
                'foto' => 'img/1733192994-7loTtJNyZ9ainOX75YGZfmqjuJs6b9I7zpEQiNkb.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:29:54',
                'updated_at' => '2024-11-19 09:29:54',
            ),
            12 => 
            array (
                'id' => 13,
                'kode_barang' => '7120',
                'kategori' => 'SPILTTER',
                'nama_barang' => 'S 1:2',
                'seri' => '-',
                'jumlah' => 2,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 2',
                'foto' => 'img/1733193053-r3f1EttkW85TdFZmdpZf2O4yDRtRfyC9qAeVV1Jh.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:30:53',
                'updated_at' => '2024-11-19 09:30:53',
            ),
            13 => 
            array (
                'id' => 14,
                'kode_barang' => '7126',
                'kategori' => 'SPLITTER RATIO',
                'nama_barang' => 'SR 90%:10%',
                'seri' => '-',
                'jumlah' => 2,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 2',
                'foto' => 'img/1733193291-zMLYrT9u9CzCrU37oQ5Fwcblu9NQx6742DGT1S0o.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:34:51',
                'updated_at' => '2024-11-19 09:34:51',
            ),
            14 => 
            array (
                'id' => 15,
                'kode_barang' => '7117',
                'kategori' => 'CPE & Aksesoris',
                'nama_barang' => 'Roset',
                'seri' => '-',
                'jumlah' => 40,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 3',
                'foto' => 'img/1733193400-5jUzDnxXzyeRWdTKqzug2huZl1ILDRIgHnZApjaB.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:36:40',
                'updated_at' => '2024-11-19 09:36:40',
            ),
            15 => 
            array (
                'id' => 16,
                'kode_barang' => '7132',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'Joint Closure',
                'seri' => 'Kotak',
                'jumlah' => 5,
                'satuan' => 'unit',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 5',
                'foto' => 'img/1733193505-JRrR6xCXOLXLqbC7lCCbl5QNnzbAuvvvStO5CdjM.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:38:25',
                'updated_at' => '2024-11-19 09:38:25',
            ),
            16 => 
            array (
                'id' => 17,
                'kode_barang' => '7134',
                'kategori' => 'Aksesoris',
                'nama_barang' => 'ODP',
                'seri' => 'Double Lock',
                'jumlah' => 5,
                'satuan' => 'pcs',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 5',
                'foto' => 'img/1733193729-JsEZO1izP5qHb0BHV9WtXzyVJ3fdNqII74mztR34.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-11-19 09:42:09',
                'updated_at' => '2024-11-19 09:42:09',
            ),
            17 => 
            array (
                'id' => 18,
                'kode_barang' => 'gfgf',
                'kategori' => 'SPLITTER RATIO',
                'nama_barang' => 'Kabel Ties',
                'seri' => '-',
                'jumlah' => 0,
                'satuan' => 'pack',
                'rasio' => NULL,
                'hasil' => NULL,
                'detail_jumlah' => NULL,
                'lokasi' => 'Rak 5',
                'foto' => 'img/1733199456-pXaCEWW7LM0qWDdDncvdrdrfk7zgEZuq0YHcKVRu.jpg',
                'input_by' => 'Kevin PKL',
                'keterangan' => NULL,
                'pop' => 'G1',
                'created_at' => '2024-12-03 11:17:36',
                'updated_at' => '2024-12-03 11:18:01',
            ),
        ));
        
        
    }
}